### ISSUE TITLE
 Line magic function `%` not found.

### ISSUE THREAD

**Issue by MonitSharma** [dair-ai/ML-Notebooks#19]
In the tutorial related to the [CounterFactual Explainations](https://colab.research.google.com/drive/1mTSRjqki3VsH9MVPfNtJ5nJxcCHvL8B6?usp=sharing#scrollTo=AqOxGWuAuNAG), when we clone the `cogs` repo, , we use 
```python
# clone repo, access, and install repo
! git clone https://github.com/marcovirgolin/cogs
% cd /content/cogs
! pip install .

```
Running this block would give an error ` Line magic function  % not found.`

The change directory command line is actually three words, but with Ubuntu 18.04, Python 3.8 and iPython 7.19, it actually needs two words, and not three. Since most of the devices use these versions now, it would be helpful to just remove the extra space between the `%` and `cd`.

The changed code would look like this:
```python
# clone repo, access, and install repo
! git clone https://github.com/marcovirgolin/cogs
%cd /content/cogs
! pip install .

```

**Comment by omarsar** [comment]
Thanks for reporting. Looking into this soon.
